name: dagster_demo
version: 1.0.0
config-version: 2

profile: dagster_demo

model-paths:
  - models
seed-paths:
  - seeds
analysis-paths:
  - analyses
test-paths:
  - tests
target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  dagster_demo:
    +materialized: table
